name:                BnV-Stellar-Simulator
version:             0.1.0.0
github:              "githubuser/BnV-Stellar-Simulator"
license:             BSD-3-Clause
author:              "José Vergara"
maintainer:          "josea.vergara2005@gmail.com"
copyright:           "2025 José Vergara"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/BnV-Stellar-Simulator#readme>

dependencies:
- base >= 4.7 && < 5
- gloss

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  BnV-Stellar-Simulator-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - BnV-Stellar-Simulator
